### ISSUE TITLE
"Imprimer mes notes" shows another user's name at the top of the page 

### ISSUE THREAD

**Issue by rcostain** [SN-RECIT-formation-a-distance/moodle-mod_recitcahiertraces#1]
Printing "All my Notes" shows a seemingly random instructor/manager name from the course at the top of the page.
<img width="742" alt="image" src="https://github.com/SN-RECIT-formation-a-distance/moodle-mod_recitcahiertraces/assets/16578976/600f9fa8-862a-457d-aab0-ea73418c724c">

**Comment by gustavobazzo** [comment]
Hello @rcostain,

Thank you for reporting this issue.

This was fixed on version [v2.3.9-stable](https://github.com/SN-RECIT-formation-a-distance/moodle-mod_recitcahiertraces/releases/tag/v2.3.9-stable)

Kind regards,
